import type { Metadata } from "next";
import { myFont } from "./fonts";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} ${myFont.className}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
